name: E2E Tests

on:
  push:
    branches: [ main, feature/preorder-functionality ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run E2E tests
      env:
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        SHOPIFY_STORE_PASSWORD: ${{ secrets.SHOPIFY_STORE_PASSWORD }}
        PREORDER_PRODUCT: ${{ secrets.PREORDER_PRODUCT }}
        REGULAR_PRODUCT: ${{ secrets.REGULAR_PRODUCT }}
      run: npm run test:ci
    
    - name: Upload test screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-screenshots
        path: tests/screenshots/
        retention-days: 7
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          jest-results.json
          coverage/
        retention-days: 30